apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: python-zvxrypmi
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/python-zvxrypmi:9642544fbb22c07aa3a10958c8cb314370174375@sha256:aede22de699a7b38abe71ce5b284d758acf5a029f06716003e8342c6458cc6e0
        name: container-image  
